var products = [ 
    { 
     "id": 0,
     "name" : 'URBAN ALCHEMY',
     "smallDesc": 'SALT SCRUB CLEANSE SHAMPOO',
     "price" : "$20.0",
     "image":   '../assets/images/scrub-shampoo.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    'howtouse': 'Before using The Airshot, ensure that the hair is thoroughly towel dried. <br> To quickly blast dry hair, use without fixing a nozzle. <br> For precision drying, fix either the 60mm or 75mm nozzle. <br> When the hair is dry, fix in the style by pressing the Cold Shot Button and continue drying the hair for a further 2 minutes.'
    },
    { 
     "id": 1,
     "name" : 'CALMING CONDITIONER',
     "smallDesc": 'SO PURE NATURAL BALANCE',
     "price" : "$23.0",
     "image": '../assets/images/conditioner.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "name" : '3Deluxe',
     "smallDesc": 'Nutritive Mask',
     "price" : "$50.0",
     "image": '../assets/images/mask.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "name" : '3Deluxe',
     "smallDesc": 'Lakmé Teknia',
     "price" : "$50.0",
     "image": '../assets/images/shampoo.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "name" : 'URBAN ALCHEMY',
     "smallDesc": 'SALT SCRUB CLEANSE SHAMPOO',
     "price" : "$20.0",
     "image": '../assets/images/scrub-shampoo.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 5,
     "name" : 'CALMING CONDITIONER',
     "smallDesc": 'SO PURE NATURAL BALANCE',
     "price" : "$23.0",
     "image": '../assets/images/conditioner.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 6,
     "name" : '3Deluxe',
     "smallDesc": 'Nutritive Mask',
     "price" : "$50.0",
     "image": '../assets/images/mask.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 7,
     "name" : '3Deluxe',
     "smallDesc": 'Lakmé Teknia',
     "price" : "$50.0",
     "image": '../assets/images/shampoo.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 1,
     "name" : 'URBAN ALCHEMY',
     "smallDesc": 'SALT SCRUB CLEANSE SHAMPOO',
     "price" : "$20.0",
     "image": '../assets/images/scrub-shampoo.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "name" : 'CALMING CONDITIONER',
     "smallDesc": 'SO PURE NATURAL BALANCE',
     "price" : "$23.0",
     "image": '../assets/images/conditioner.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "name" : '3Deluxe',
     "smallDesc": 'Nutritive Mask',
     "price" : "$50.0",
     "image": '../assets/images/mask.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "name" : '3Deluxe',
     "smallDesc": 'Lakmé Teknia',
     "price" : "$50.0",
     "image": '../assets/images/shampoo.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
 ]

var equipments = [ 
    { 
     "id": 1,
     "name" : 'CLOUD NINE Sericite',
     "smallDesc": 'Professional Wide Iron',
     "price" : "$20.0",
     "image":   '../assets/images/iron.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "name" : 'CLOUD NINE Sericite',
     "smallDesc": 'Professional Airshot Hair Dryer',
     "price" : "$23.0",
     "image": '../assets/images/dryer.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "name" : 'DIVA',
     "smallDesc": 'MK11 Ceramic & Tourmaline Pink Straightener',
     "price" : "$50.0",
     "image": '../assets/images/diva.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "name" : 'Hi CURL',
     "smallDesc": 'Hi Curl Ceramic & Tourmaline Curling Iron 19mm',
     "price" : "$50.0",
     "image": '../assets/images/curl.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 1,
     "name" : 'CLOUD NINE Sericite',
     "smallDesc": 'Professional Wide Iron',
     "price" : "$20.0",
     "image":   '../assets/images/iron.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "name" : 'CLOUD NINE Sericite',
     "smallDesc": 'Professional Airshot Hair Dryer',
     "price" : "$23.0",
     "image": '../assets/images/dryer.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "name" : 'DIVA',
     "smallDesc": 'MK11 Ceramic & Tourmaline Pink Straightener',
     "price" : "$50.0",
     "image": '../assets/images/diva.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "name" : 'Hi CURL',
     "smallDesc": 'Hi Curl Ceramic & Tourmaline Curling Iron 19mm',
     "price" : "$50.0",
     "image": '../assets/images/curl.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 1,
     "name" : 'CLOUD NINE Sericite',
     "smallDesc": 'Professional Wide Iron',
     "price" : "$20.0",
     "image":   '../assets/images/iron.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "name" : 'CLOUD NINE Sericite',
     "smallDesc": 'Professional Airshot Hair Dryer',
     "price" : "$23.0",
     "image": '../assets/images/dryer.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "name" : 'DIVA',
     "smallDesc": 'MK11 Ceramic & Tourmaline Pink Straightener',
     "price" : "$50.0",
     "image": '../assets/images/diva.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "name" : 'Hi CURL',
     "smallDesc": 'Hi Curl Ceramic & Tourmaline Curling Iron 19mm',
     "price" : "$50.0",
     "image": '../assets/images/curl.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    
 ]

var remedies = [ 
    { 
     "id": 0,
     "title" : 'How To Get Silky And Bouncy Hair In Summer?',
     "smallDesc": 'Don’t let the heat bring you down – follow some simple tips to get luscious hair..',
     "lastUpdate" : "Last updated 3 mins ago",
     "image":   '../assets/images/post1.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 1,
     "title" : 'Home Remedies For An Itchy Scalp',
     "smallDesc": 'Remedies that work instantly and help relieve itching before it worsens..',
     "lastUpdate" : "Last updated 30 mins ago",
     "image":   '../assets/images/p2.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "title" : 'How To Get Rid Of Head Lice Using Olive Oil',
     "smallDesc": 'Understand how this oil may help you remove head lice at home effectively...',
     "lastUpdate" : "Last updated 1 hr ago",
     "image":   '../assets/images/post3.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "title" : 'How To Get Silky And Bouncy Hair In Summer?',
     "smallDesc": 'Don’t let the heat bring you down – follow some simple tips to get luscious hair..',
     "lastUpdate" : "Last updated 3 mins ago",
     "image":   '../assets/images/post1.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "title" : 'Home Remedies For An Itchy Scalp',
     "smallDesc": 'Remedies that work instantly and help relieve itching before it worsens..',
     "lastUpdate" : "Last updated 30 mins ago",
     "image":   '../assets/images/p2.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 5,
     "title" : 'How To Get Rid Of Head Lice Using Olive Oil',
     "smallDesc": 'Understand how this oil may help you remove head lice at home effectively...',
     "lastUpdate" : "Last updated 1 hr ago",
     "image":   '../assets/images/post3.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
   
 ]

 