var products = [ 
    { 
     "id": 0,
     "title" : 'SALT SCRUB CLEANSE SHAMPOO',
     "brand": '360',
     'smallDesc': 'Designed to elevate natural curl patterns, elasticity and vitality of curly hair types. Define and control curly and wavy hair with the 360 Be Curl Shampoo.',
     "price" : "$20.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/7519b5ff041047da87c8acdfc292df3b/53340_360_be20curl20shampoo_450ml_front.png',
     "productInfo": "<ul> <li> Elevates natural curl pattern </li>  <li> Promotes elasticity and vitality </li> <li> Contains Honey and Vitamin C to help define curls </li> <li> Free from cruelty, parabens and mineral oil </li> <li> Made with recyclable packaging </li> <li> Suitable for curly and wavy hair types </li> </ul> The recommended retail price (RRP) for this item is $16.95. 360 Be Curl Shampoo is part of 360's three-step curl system. Created with nourished, conditioned and full-of-life curls in mind, this range has been formulated with Honey and Vitamin C to nourish and define. Heat styling can have a damaging effect on curls, but this range has been designed to help revive those natural curl patterns. This defining and controlling shampoo effectively cleans the hair and scalp, whilst elevating natural curl patterns, elasticity and vitality of the hair. 360 Gentle on hair and its environment, 360 Color is a collection of cruelty, paraben and gluten free permanent hair colour creams. Designed for busy salons, 360 Color is a high performing range with an economical price tag.",
     'howtouse': '<ul><li>Apply Be Curl Shampoo to wet hair, massaging product into the scalp </li> <li> Rise thoroughly </li> <li> For best results, use in conjunction with 360 Be Curl Conditioner </li> </ul>',
     'maintenance': 'maintenance',
    },
    { 
     "id": 1,
     "title" : 'BE LISS HEAT PROTECTION CREAM',
     "brand": '360',
     'smallDesc': 'A heat protection cream formulated with nourishing ingredients to leave the hair stronger and healthier. Achieve shiny, smooth results with Be Liss Heat Protection Cream by 360.',
     "price" : "$24.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/e9ff801067bc47d08d3650cb7f8fb484/53442_360_be20liss20cream_250ml_front.png',
     "productInfo": "<ul> <li>Hair styling cream with up to 180°C heat protection</li><li>Adds softness and shine while achieving long-lasting smoothness</li><li>Strengthens hair and helps reduce breakage</li><li>Hydrates and conditions, making detangling easier</li><li>Disciplines unruly hair and controls frizz</li> <li>Creates flawless results with a blow-dryer or flat iron</li> </ul> The recommended retail price (RRP) for this item is $24.95. 360 Be Liss Heat Protection Cream is your new best friend in salon when it comes to heat styling. Designed to offer heat protection up to 180°C, Be Liss helps you achieve smooth, shiny and flawless results. Formulated with nourishing ingredients, this heat protection cream leaves hair feeling stronger and healthier. Be Liss hydrates and conditions, making frizzy and unruly hair easier to detangle and manage. Discover your in-salon secret weapon and the perfect product to send your clients home with. 360 Gentle on hair and its environment, <br> <strong>360<strong> Color is a collection of cruelty, paraben and gluten free permanent hair colour creams. Designed for busy salons, <strong>360<strong> Color is a high performing range with an economical price tag.",
     'howtouse': 'Apply Be Liss Cream from mid-lengths to ends of clean, damp towel-dried hair. Do not rinse. <br> Blow-dry and/or straighten with an iron for smooth results.',
     'maintenance': 'maintenance',
    },
    { 
     "id": 2,
     "title" : 'MAXI GEL',
     "brand": '360',
     'smallDesc': 'A wet-look gel that provides medium to strong hold and creates natural definition in all hair types.',
     "price" : "$19.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/c18b2f26ccb54eb69dced6bb3961939b/53430_360c_maxi20gel_500ml_front_transparent_27052020.png',
     "productInfo": "<ul><li>Versatile application on wet or dry hair</li><li>Helps make blow-drying easier by creating natural definition and hold</li><li>Vegan friendly</li><li>Free from parabens, gluten and mineral oils</li><li>Recommended for all hair types</li></ul>The recommended retail price (RRP) for this item is $19.95. 360 Maxi Gel is a modern, versatile wet-look styling gel; suitable for all hair types. This hair styling gel provides a medium to strong hold, and can easily be applied to wet or dry hair. When blow-dried in, Maxi Gel helps to create natural definition and hold. Formulated without parabens, gluten or mineral oils, this styling essential is vegan-friendly. <br> <strong>360<strong> Color is a high performing range with an economical price tag.",
     'howtouse': 'Work gel through damp or dry hair and style as desired.<br>Blow-dry into hair to create natural definition.',
     'maintenance': 'maintenance',
    },
    { 
     "id": 3,
     "title" : 'EXTREME HOLD HAIRSPRAY',
     "brand": '3DELUXE',
     'smallDesc': 'An extreme hold hairspray with high shine and no residue. Use 3Deluxe Extreme Hairspray for added control and volume in hair..',
     "price" : "$25.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/af71cb8284444548a037cf7eadbd0fa3/44530_3d_extreme20hold20hairspray_500ml_front_29102020.png',
     "productInfo": "<ul><li>Styling spray with extreme hold and no residue</li><li>Argan Oil protects and softens</li><li>Doubles as an intense shine spray</li><li>Provides control and volume</li><li>Suitable for all hair types</li></ul>The recommended retail price (RRP) for this item is $25.95. 3Deluxe Professional features a luxurious hair collection infused with natural ingredients, crafted for unique salon experiences with sensorial textures and calming fragrances. Extreme Hairspray offers an intense hold without the flaky residue. This extreme hairspray doubles as a high shine spray, with an infusion of Argan Oil to maintain moisture and protect the hair fibre. 3Deluxe Extreme Hairspray provides optimal control and added volume, and is suitable for all hair types.<br> <strong>3DELUXE<strong>",
     'howtouse': 'Hold the spray nozzle at least 30cm from hair.<br>Spray the fine mist in a continuous motion. <br> Smooth down any broken or baby hairs.',
     'maintenance': 'maintenance',
    },
    { 
     "id": 4,
     "title" : 'NUTRITIVE SHAMPOO',
     "brand": '3DELUXE',
     'smallDesc': 'A nourishing shampoo for enhancing softness. Use Nutritive Shampoo for dry or unruly hair.',
     "price" : "$19.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/7873883b8c3c4814bdfdbaae7b1f0df1/44503_3d_nutritive20shamoo_1l_front_11052020.png',
     "productInfo": "<ul><li>Nourishing shampoo that enhances softness</li><li>Recommended for dry or unruly hair</li><li>Argan Oil and Honey protect and moisturise while reducing breakage</li><li>Luxurious fragrance of Sweet Almond, Karite, Argan, Honey and Ebony Wood</li></ul>3Deluxe Professional features a luxurious hair collection infused with natural ingredients, crafted for unique salon experiences with sensorial textures and calming fragrances. Extreme Hairspray offers an intense hold without the flaky residue. This extreme hairspray doubles as a high shine spray, with an infusion of Argan Oil to maintain moisture and protect the hair fibre. 3Deluxe Extreme Hairspray provides optimal control and added volume, and is suitable for all hair types. <br> <strong>3DELUXE<strong>",
     'howtouse': 'Apply Nutritive Shampoo to wet hair.<br>Massage gently, then rinse.<br>If shampoo comes into contact with eyes, rinse immediately.',
     'maintenance': 'maintenance',
    },
    { 
     "id": 5,
     "title" : 'COLOR MASK WIT CAP & PUMP',
     "brand": '3DELUXE',
     'smallDesc': 'A radiant mask for maintaining and preserving colour intensity. Use 3Deluxe Color Mask on coloured hair.',
     "price" : "$22.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/8efa560636b54df099a7cf9347f6f404/44512_3d_color20mask_1l_front_11052020.png',
     "productInfo": "This kit includes: <br> <ul><li>1 x Color Mask</li><li>1 x Cap & Pump Jar</li><li>Maintains hair colour intensity</li><li>Sweet Almond Extracts condition and hydrate dry hair fibres</li><li>Recommended for coloured hair</li><li>Luxurious fragrance of Pineapple, Lychees, Camellia, Vanilla and Tonka Bean</li><li>Comes with bonus pump</li></ul>3Deluxe Professional features a luxurious hair collection infused with natural ingredients, crafted for unique salon experiences with sensorial textures and calming fragrances. Extreme Hairspray offers an intense hold without the flaky residue. This extreme hairspray doubles as a high shine spray, with an infusion of Argan Oil to maintain moisture and protect the hair fibre. 3Deluxe Extreme Hairspray provides optimal control and added volume, and is suitable for all hair types. <br> <strong>3DELUXE<strong>",
     'howtouse': 'Apply to clean, towel dried hair, focusing on lengths and ends.<br>Leave for 20-30 minutes, then rinse with lukewarm water.',
     'maintenance': 'maintenance',
    },
    { 
     "id": 6,
     "title" : 'XTRA LARGE BOMBSHELL VOLUMIZER',
     "brand": 'COLOR WOW',
     'smallDesc': 'A hair volumising foam with a Bamboo blend to thicken and build body in fine, thin or limp hair. Create voluminous body that lasts for days with Xtra Large Bombshell Volumizer by Color Wow.',
     "price" : "$63.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/565bc90d93cf4dee8d317651aca9674e/77860_color20wow_xtra20large20bombshell20volumizer_200ml_front.png',
     "productInfo": "<ul><li>Hair volumising foam that creates serious texture and body</li><li>Polymer and Bamboo blend thickens while keeping the hair cuticle intact</li><li>Features a non-damaging, non-dehydrating and non-invasive formula that delivers body and grip without compromising hair health</li><li>Hair is left soft and touchable, not sticky or crunchy</li><li>Designed to give fine, limp, thin or flat hair bold bombshell finishes</li><li>Safe for use on colour-treated hair</li> </ul>The recommended retail price (RRP) for this item is $63.00. Color Wow's highly anticipated Xtra Large Bombshell Volumiser delivers exceptional body, lift and texture to fine, flat, thin or limp hair. Color Wow has formulated Xtra Large Bombshell Volumiser without the typical thickening ingredients like alcohol, salt or resins commonly found in volumising products. Instead, this volumising foam features a proprietary blend of Polymer and Bamboo that surrounds each hair strand, creating a cuticle lift without compromising the integrity of hair. Xtra Large leaves hair feeling soft and touchable - not sticky or crunchy, and gives flimsy hair new 'guts and grab' texture that can hold bold styles. Hair is left smooth, hydrated and visibly larger! <br> <strong>COLOR WOW<strong>  was created to solve beauty problems with high performing formulas that enhance hair colour services — giving salon professionals a smarter, faster and safer way to style coloured hair.",
     'howtouse': 'Apply to damp hair.<br>Add 2-3 pumps to hands and work through roots to ends, section by section. Continue until all hair is covered. <br> Comb through to distribute evenly. <br> Xtra Large Bombshell Volumizer can be blow-dried or air-dried.',
     'maintenance': 'maintenance',
    },
    { 
     "id": 7,
     "title" : 'SPEED DRY BLOW DRY SPRAY',
     "brand": 'COLOR WOW',
     'smallDesc': 'A heat protection styling spray to promote faster, less damaging blow-drying. Protect colour vibrancy and keep hair hydrated with Speed Dry Blow Dry Spray by Color Wow.',
     "price" : "$50.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/f1c0bc63b9cd478eb82bd8d9fd2f7758/78855_color20wow_speed20dry20blow20dry20spray_150ml_front.png',
     "productInfo": "<ul><li>Heat protection blow-drying spray</li><li>Speeds up blow-drying time to reduce breakage caused by tension and over-heating</li><li>Proprietary polymers squeeze out excess water while infusing essential hydration into each hair fibre</li><li>Keratin Proteins, Panthenol and Silk Amino Acids increase elasticity and strength</li><li>Never tested on animals</li><li>Free from alcohol, silicone, parabens, sulphates & gluten</li><li>Suitable for all hair types; especially colour-treated, dry or damaged hair</li> </ul>The recommended retail price (RRP) for this item is $50.00. For hair that is especially prone to breakage and colour-fading, Color Wow Speed Dry Blow Dry Spray dramatically increases blow-drying time to minimise damage cause by excessive exposure to heat. When hair is frequently exposed to the tension and dehydration caused by heat styling, it can dry out, break and fade. Speed Dry reduces this styling time with an alcohol-free formula containing proprietary polymers to wick away water droplets while locking in essential moisture into each hair fibre. A blend of Keratin Proteins, Panthenol and Silk Amino Acids help boost the hair's elasticity, strength, and resilience. Highly recommended for colour-treated, dry or damaged hair, Speed Dry is free from silicones, parabens, sulphates, gluten and never tested on animals, so your clients know their hair is cared for. <br> <strong>COLOR WOW<strong>  was created to solve beauty problems with high performing formulas that enhance hair colour services — giving salon professionals a smarter, faster and safer way to style coloured hair.",
     'howtouse': 'Shampoo, condition, then towel-dry hair.<br>Spray Speed Dry liberally over hair the comb through.<br>Follow with desired styling products then blow-dry to finish.<br>If desired, apply Dream Cocktails before Speed Dry. There is no need to use Speed Dry with Dream Coat.',
     'maintenance': 'maintenance',
    },

    { 
     "id": 8,
     "title" : 'SCALP CARE DETOX SHAMPOO',
     "brand": 'LAKMÉ TEKNIA',
     'smallDesc': 'A balance micellar shampoo to combat dry and oily dandruff. Deep cleanse the scalp and regulate cell renewal with TEKNIA Scalp Care Detox Shampoo by Lakmé.',
     "price" : "$50.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/24eae7d17d2a4501bc236e6e69d099e8/56430_lakme_teknia20scalp20care20detox20shampoonew_1l_front.png',
     "productInfo": "<ul><li>Micellar shampoo to combat dry or oily dandruff</li><li>BIOME Oléoactif® for a balanced and strengthened microbiota</li><li>Crinipan® regulates cell renewal  and visibly reduces scales and prevents their formation</li><li>Includes natural menthol as an antiseptic with a refreshing effect</li><li>Results in a soft scalp free of scales, redness and irritations</li><li>Fresh mint fragrance with balsamic notes and tangerine essential oil</li></ul>TEKNIA Scalp Care is a line of products designed to treat the root problem in order to protect, soothe,  nourish, and rebalance the scalp. Formulated with BIOME OLÉOACTIF®, the first post-prebiotic complex on the market, that promotes the growth of healthy bacteria against pathogenic bacteria. The Detox product line has been designed to balance the scalp's microbiota and combat oily and dry dandruff. TEKNIA Scalp Care Detox Shampoo is a micellar shampoo that deeply cleanses the scalp and reduces dandruff by up to 80%. It's combination of active ingredients inhibits microorganisms that cause flaking, strengthening the hair's natural defenses. A vegan formula with 94% naturally derived ingredients. <br> <strong>LAKMÉ TEKNIA<strong>Created by stylists, the Lakmé hair collection is committed to innovation and sustainability. With its Mediterranean origins, traditional values and beauty have inspired Lakmé salon colours, tools and products.",
     'howtouse': 'Shampoo, condition, then towel-dry hair.<br>Spray Speed Dry liberally over hair the comb through.<br>Follow with desired styling products then blow-dry to finish.<br>If desired, apply Dream Cocktails before Speed Dry. There is no need to use Speed Dry with Dream Coat.',
     'maintenance': 'maintenance',
    },
    { 
     "id": 9,
     "title" : 'SCALP CARE PURE MASK',
     "brand": 'LAKMÉ TEKNIA',
     'smallDesc': 'A pre-shampoo mask that detoxifies, cleanses, absorbs oil and leaves scalp free from impurities. Rebalance and protect the scalp`s microbiota with TEKNIA Scalp Care Pure Mask by Lakmé.',
     "price" : "$64.0",
     "image":   'https://www.thehaircaregroup.com/contentassets/e5dd65e62a9a480eb5f846c1676dba2e/56442_lakme_teknia20pure20mask_250ml_front.png',
     "productInfo": "<ul><li>Detoxifies, cleanses and absorbs oiliness</li><li>Effective against excess sebum and impurities</li><li>BIOME Oléoactif® for a balanced and strengthened microbiota</li><li>Natural clay absorbs excess sebum</li><li>Zincdione reduces sebum secretion by regulating the sebaceous gland</li><li>Fresh mint fragrance with balsamic notes and tangerine essential oil</li></ul>The recommended retail price (RRP) for this item is $64.95. TEKNIA Scalp Care is a line of products designed to treat the root problem in order to protect, soothe,  nourish, and rebalance the scalp. Formulated with BIOME OLÉOACTIF®, the first post-prebiotic complex on the market, that promotes the growth of healthy bacteria against pathogenic bacteria. The Pure product line has been designed to cleanse, purify and regulate excess oil. TEKNIA Scalp Care Pure Mask is a pre-shampoo mask that detoxifies, cleanses, absorbs oil and leaves scalp free from impurities, reducing scalp oiliness by 66%. A vegan formula with 98% naturally derived ingredients.<br> <strong>LAKMÉ TEKNIA<strong>Created by stylists, the Lakmé hair collection is committed to innovation and sustainability. With its Mediterranean origins, traditional values and beauty have inspired Lakmé salon colours, tools and products.",
     'howtouse': 'Shampoo, condition, then towel-dry hair.<br>Spray Speed Dry liberally over hair the comb through.<br>Follow with desired styling products then blow-dry to finish.<br>If desired, apply Dream Cocktails before Speed Dry. There is no need to use Speed Dry with Dream Coat.',
     'maintenance': 'maintenance',
    },
     
 ]

var equipments = [ 
    { 
     "id": 1,
     "name" : 'CLOUD NINE Sericite',
     "brand": 'Professional Wide Iron',
     "price" : "$20.0",
     "image":   '../assets/images/iron.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "name" : 'CLOUD NINE Sericite',
     "brand": 'Professional Airshot Hair Dryer',
     "price" : "$23.0",
     "image": '../assets/images/dryer.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "name" : 'DIVA',
     "brand": 'MK11 Ceramic & Tourmaline Pink Straightener',
     "price" : "$50.0",
     "image": '../assets/images/diva.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "name" : 'Hi CURL',
     "brand": 'Hi Curl Ceramic & Tourmaline Curling Iron 19mm',
     "price" : "$50.0",
     "image": '../assets/images/curl.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 1,
     "name" : 'CLOUD NINE Sericite',
     "brand": 'Professional Wide Iron',
     "price" : "$20.0",
     "image":   '../assets/images/iron.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "name" : 'CLOUD NINE Sericite',
     "brand": 'Professional Airshot Hair Dryer',
     "price" : "$23.0",
     "image": '../assets/images/dryer.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "name" : 'DIVA',
     "brand": 'MK11 Ceramic & Tourmaline Pink Straightener',
     "price" : "$50.0",
     "image": '../assets/images/diva.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "name" : 'Hi CURL',
     "brand": 'Hi Curl Ceramic & Tourmaline Curling Iron 19mm',
     "price" : "$50.0",
     "image": '../assets/images/curl.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 1,
     "name" : 'CLOUD NINE Sericite',
     "brand": 'Professional Wide Iron',
     "price" : "$20.0",
     "image":   '../assets/images/iron.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "name" : 'CLOUD NINE Sericite',
     "brand": 'Professional Airshot Hair Dryer',
     "price" : "$23.0",
     "image": '../assets/images/dryer.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "name" : 'DIVA',
     "brand": 'MK11 Ceramic & Tourmaline Pink Straightener',
     "price" : "$50.0",
     "image": '../assets/images/diva.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "name" : 'Hi CURL',
     "brand": 'Hi Curl Ceramic & Tourmaline Curling Iron 19mm',
     "price" : "$50.0",
     "image": '../assets/images/curl.png',
     "longDesc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    
 ]

var remedies = [ 
    { 
     "id": 0,
     "title" : 'How To Get Silky And Bouncy Hair In Summer?',
     "brand": 'Don’t let the heat bring you down – follow some simple tips to get luscious hair..',
     "lastUpdate" : "Last updated 3 mins ago",
     "image":   '../assets/images/post1.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 1,
     "title" : 'Home Remedies For An Itchy Scalp',
     "brand": 'Remedies that work instantly and help relieve itching before it worsens..',
     "lastUpdate" : "Last updated 30 mins ago",
     "image":   '../assets/images/p2.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 2,
     "title" : 'How To Get Rid Of Head Lice Using Olive Oil',
     "brand": 'Understand how this oil may help you remove head lice at home effectively...',
     "lastUpdate" : "Last updated 1 hr ago",
     "image":   '../assets/images/post3.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 3,
     "title" : 'How To Get Silky And Bouncy Hair In Summer?',
     "brand": 'Don’t let the heat bring you down – follow some simple tips to get luscious hair..',
     "lastUpdate" : "Last updated 3 mins ago",
     "image":   '../assets/images/post1.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 4,
     "title" : 'Home Remedies For An Itchy Scalp',
     "brand": 'Remedies that work instantly and help relieve itching before it worsens..',
     "lastUpdate" : "Last updated 30 mins ago",
     "image":   '../assets/images/p2.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
    { 
     "id": 5,
     "title" : 'How To Get Rid Of Head Lice Using Olive Oil',
     "brand": 'Understand how this oil may help you remove head lice at home effectively...',
     "lastUpdate" : "Last updated 1 hr ago",
     "image":   '../assets/images/post3.png',
     "encodedHTMLArticlecontent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
     },
   
 ]

 